### ISSUE TITLE
 The miner creates blocks, without being connected to the chain 

### ISSUE THREAD

**Issue by kalekoi** [elichai/kaspa-miner#5]
Connect the new miner 0.1.1 and began to create blocks many blocks and closed, the kaspa client says that they are orphans and you have no parents and keeps looking.

**Comment by elichai** [comment]
Can you post the logs of both kaspa-miner and kaspad? Thanks!

**Comment by kalekoi** [comment]
It seems to be from the Kaspa client and not from the miner. Thanks also
