### ISSUE TITLE
Speedup suggestion

### ISSUE THREAD

**Issue by orik-foxface** [elichai/kaspa-miner#8]
I don't speak rust so it'll take me forever to implement, but if you pass the target to heavy_hash then you you can stop populating the result as soon as it becomes clearly larger

`let data: [u8; 32] = array_from_fn(|i| hash[i] ^ ((product[i * 2] << 4) as u8 | product[2 * i + 1] as u8));
`

Same for matrix multiplication right above it. So overall - do one row multiplication, then calculate one byte of data, compare to byte in target and continue only if necessary.

**Comment by elichai** [comment]
There is a hash after this matrix-vector multiplication, you can see that the data is then passed into another hash function: https://github.com/elichai/kaspa-miner/blob/90e6f5391f68db57447127bd989ada0834608b77/src/pow/heavy_hash.rs#L99-L101
So this optimization shouldn't be necessary
